### ISSUE TITLE
Adding a TOC (table of contents) to the docx template causes error in recipe when generating

### ISSUE THREAD

**Issue by manemal** [jsreport/jsreport-docx#11]
### Clarification
Firstly, this is **NOT** to request JSReport docx recipe support (re)generating TOC's, as clearly this would be a complex undertaking to replicate that functionality.

Instead, this is to request that the docx recipe ignore the hyperlinks within the generated TOC, present in the docx template file.

If templating is present around document sections then, yes, potentially the TOC will not reflect the sections present in the generated document.  However, this is a common problem with other templating solutions and the same solution applies here too - load the document into the application and update all field codes (F9) or similar procedures.  Not ideal, but it is what it is.

### Error presented:
```
Error: Error while executing docx recipe. Cannot read property 'cloneNode' of undefined
    at module.exports (D:\Temp\jsreport-2.7.2\JSReport.Dev.Studio\node_modules\jsreport-core\lib\util\createError.js:11:13)
    at Reporter.createError (D:\Temp\jsreport-2.7.2\JSReport.Dev.Studio\node_modules\jsreport-core\lib\reporter.js:328:12)
    at Object.execute (D:\Temp\jsreport-2.7.2\JSReport.Dev.Studio\node_modules\jsreport-docx\lib\recipe.js:62:20)
caused by: TypeError: Cannot read property 'cloneNode' of undefined
    at processHyperlinks (D:\Temp\jsreport-2.7.2\JSReport.Dev.Studio\node_modules\jsreport-docx\lib\preprocess\link.js:72:49)
    at module.exports (D:\Temp\jsreport-2.7.2\JSReport.Dev.Studio\node_modules\jsreport-docx\lib\preprocess\link.js:13:5)
    at module.exports (D:\Temp\jsreport-2.7.2\JSReport.Dev.Studio\node_modules\jsreport-docx\lib\preprocess\preprocess.js:11:3)
    at scriptDocxProcessing (D:\Temp\jsreport-2.7.2\JSReport.Dev.Studio\node_modules\jsreport-docx\lib\scriptDocxProcessing.js:51:11)
```
### More information:
Both in the pre- and post-processing of the docx recipe, it collates all the hyperlinks defined in the document to then process them, looking for templated targets to resolve? (I'm guessing).
The problem is that there are hyperlinks within a table of contents (which link to the different sections in the document) that do not match the pattern the recipe is looking for, to process.  This results in the error reported above.

Essentially the TOC hyperlinks do not have an **Id** attribute so the subsequent logic (filtering and cloning in pre-process) fails.  This also applies to the processElement() function when processing hyperlinks in the post-process stage.
### Example report
https://playground.jsreport.net/w/manemal/GpXMxbvf

**Comment by pofider** [comment]
Thank you for the problem description. We will review it shortly and come back to you.

**Comment by bjrmatos** [comment]
@manemal thanks for the issue report, and sorry for the long wait, we have been busy working on other features. the problem should be fixed on master, the rendering no longer breaks when finding hyperlinks that reference content in the document (like your TOC). you can test it by installing from git `npm install jsreport/jsreport-docx`. let us know if you find some other issue
