### ISSUE TITLE
radarChart support

### ISSUE THREAD

**Issue by NickBok** [jsreport/jsreport-docx#33]
Is the radar chart supported?
tested jsreport v 2.11.0
`Error: Error while executing docx recipe. Chart "radarChart" type is not supported, ref: "word/charts/chart9.xml"
    at module.exports (/app/node_modules/jsreport-core/lib/util/createError.js:11:13)
    at Reporter.createError (/app/node_modules/jsreport-core/lib/reporter.js:332:12)
    at Object.execute (/app/node_modules/jsreport-docx/lib/recipe.js:58:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/app/node_modules/jsreport-core/lib/render/render.js:150:5)
caused by: Error: Chart "radarChart" type is not supported, ref: "word/charts/chart9.xml"
    at processChart (/app/node_modules/jsreport-docx/lib/postprocess/processChart.js:395:17)
    at /app/node_modules/jsreport-docx/lib/postprocess/drawingObject.js:71:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

Any workaround for this?

**Comment by pofider** [comment]
Only the following charts are currently supported: waterfall, treemap, sunburst, funnel, clusteredColumn.
We will look into implementing further charts soon. Just a bit busy now with releasing jsreport v3, but we get to this soon.
